# -*- coding: utf-8 -*-
"""rockpaperscissor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L11TJnAHXRD8nl4zlkZ3lEUMmu5fm70d
"""

from tkinter import *
import random
name=input("ENTER YOUR NAME")

# Create Object
root = Tk()

# Set geometry
root.geometry("350x350")

# Set title
root.title("Venky game")

# Computer Value
computer_value = {"0": "Rock","1": "Paper","2": "Scissor"}

# Reset The Game

def reset_game():
	b1["state"] = "active"
	b2["state"] = "active"
	b3["state"] = "active"
	l1.config(text=" ")
	l3.config(text=" ")
	l4.config(text="")
#Player			#Computer # Disable the Button

def button_disable():
	b1["state"] = "disable"
	b2["state"] = "disable"
	b3["state"] = "disable"

# If player selected rock

def isrock():
	c_v = computer_value[str(random.randint(0, 2))]
	if c_v == "Rock":
		match_result = "Match Draw"
	elif c_v == "Scissor":
		match_result = name+" Win"
	else:
		match_result = "Computer Win"
	l4.config(text=match_result)
	l1.config(text="Rock	")
	l3.config(text=c_v)
	button_disable()

# If player selected paper

def ispaper():
	c_v = computer_value[str(random.randint(0, 2))]
	if c_v == "Paper":
		match_result = "Match Draw"
	elif c_v == "Scissor":
		match_result = "Computer Win"
	else:
		match_result = name+" Win"
	l4.config(text=match_result)
	l1.config(text="Paper	 ")
	l3.config(text=c_v)
	button_disable()

# If player selected scissor

def isscissor():
	c_v = computer_value[str(random.randint(0, 2))]
	if c_v == "Rock":
		match_result = "Computer Win"
	elif c_v == "Scissor":
		match_result = "Match Draw"
	else:
		match_result = name+" Win"
	l4.config(text=match_result)
	l1.config(text="Scissor	")
	l3.config(text=c_v)
	button_disable()


# Add Labels, Frames and Button
Label(root,
	text="Rock Paper Scissor",
	font="normal 20 bold",
	fg="blue").pack(pady=20)

frame11=Frame(root)
frame11.pack()

ll1 = Label(frame11,
		text=name,
		font=10,fg="violetred4")

ll2 = Label(frame11,
		text="	VS	 ",
		font="normal 10 bold",fg="violetred4")

ll3 = Label(frame11, text="Computer", font=10,fg="violetred4")

ll1.pack(side=LEFT)
ll2.pack(side=LEFT)
ll3.pack()

frame = Frame(root)
frame.pack()

l1 = Label(frame,
		text=" ",
		font=10)
#Player
l2 = Label(frame,
		text=" VS	 ",
		font="normal 10 bold")
#
l3 = Label(frame, text=" ", font=10)
#Computer
l1.pack(side=LEFT)
l2.pack(side=LEFT)
l3.pack()

l4 = Label(root,
		text="",
		font="normal 20 bold",
		bg="white",
		width=15,
		borderwidth=2,
		relief="solid")
l4.pack(pady=20)

frame1 = Frame(root)
frame1.pack()

b1 = Button(frame1, text="Rock",
			font=10, width=7,
			command=isrock)

b2 = Button(frame1, text="Paper ",
			font=10, width=7,
			command=ispaper)

b3 = Button(frame1, text="Scissor",
			font=10, width=7,
			command=isscissor)

b1.pack(side=LEFT, padx=10)
b2.pack(side=LEFT, padx=10)
b3.pack(padx=10)

Button(root, text="Reset Game",
	font=20, fg="blue",
	bg="yellow", command=reset_game).pack(pady=20)

# Execute Tkinter
root.mainloop()